
INSERT INTO roles(role_name) values('ROLE_ADMIN');
INSERT INTO roles(role_name) values('ROLE_SR');
INSERT INTO roles(role_name) values('ROLE_COMMITTEE_LEADER');
INSERT INTO roles(role_name) values('ROLE_FADDER_LEADER');
INSERT INTO roles(role_name) values('ROLE_ANONYMOUS');
INSERT INTO roles(role_name) values('ROLE_STUDENT');
INSERT INTO roles(role_name) values('ROLE_DEVELOPER');


INSERT INTO rooms(room_name) VALUES('38');
INSERT INTO rooms(room_name) VALUES('39');
INSERT INTO rooms(room_name) VALUES('40');
INSERT INTO rooms(room_name) VALUES('41');
INSERT INTO rooms(room_name) VALUES('43 / 44');
INSERT INTO rooms(room_name) VALUES('45');
INSERT INTO rooms(room_name) VALUES('77');
INSERT INTO rooms(room_name) VALUES('78');
INSERT INTO rooms(room_name) VALUES('79 / 80');
INSERT INTO rooms(room_name) VALUES('81');
INSERT INTO rooms(room_name) VALUES('82');
INSERT INTO rooms(room_name) VALUES('Stillerom');
INSERT INTO rooms(room_name) VALUES('84');
INSERT INTO rooms(room_name) VALUES('Auditoriet');
INSERT INTO rooms(room_name) VALUES('Battlestation');
INSERT INTO rooms(room_name) VALUES('Biblioteket');
INSERT INTO rooms(room_name) VALUES('Kantina');
INSERT INTO rooms(room_name) VALUES('Vrimleområdet');
INSERT INTO rooms(room_name) VALUES('Fagstab');

INSERT INTO access_points(address) VALUES('00:21:51:60:e7:d0');
INSERT INTO access_points(address) VALUES('00:24:97:f2:92:e0');
INSERT INTO access_points(address) VALUES('00:24:97:f2:91:70');
INSERT INTO access_points(address) VALUES('00:18:74:d3:4b:90');
INSERT INTO access_points(address) VALUES('00:26:cd:d1:2e:10');
INSERT INTO access_points(address) VALUES('00:26:cb:d1:2d:a0');
INSERT INTO access_points(address) VALUES('00:17:0f:e7:2d:60');
INSERT INTO access_points(address) VALUES('00:21:55.60.e6:10');
INSERT INTO access_points(address) VALUES('dc:7b:94:34:94:90');
INSERT INTO access_points(address) VALUES('00:17:df:a6:c8:80');
INSERT INTO access_points(address) VALUES('00:17:df:a7:7c:50');
INSERT INTO access_points(address) VALUES('dc:7b:94:a4:2e:80');
INSERT INTO access_points(address) VALUES('00:26:cb:d1:2b:40');
INSERT INTO access_points(address) VALUES('00:23:04:88:d4:c0');
INSERT INTO access_points(address) VALUES('00:17:df:a7:7a:b0');
INSERT INTO access_points(address) VALUES('00:24:97:f2:93:60');
INSERT INTO access_points(address) VALUES('00:23:04:88:c1:20');
INSERT INTO access_points(address) VALUES('00:19:07:07:79:80');
INSERT INTO access_points(address) VALUES('00:24:97:f2:93:40');

INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(53, 64, 1);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(52, 65, 2);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(63, 75, 3);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(59, 65, 3);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(58, 76, 4);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(55, 70, 5);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(62, 71, 6);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(48, 66, 7);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(47, 62, 8);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(65, 73, 9);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(46, 62, 9);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(52, 72, 9);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(43, 65, 10);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(38, 59, 11);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(51, 62, 12);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(59, 76, 13);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(61, 71, 14);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(61, 80, 15);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(61, 70, 16);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(61, 71, 17);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(55, 62, 18);
INSERT INTO access_fields(min_range, max_range, accessPoint_id) VALUES(50, 69, 19);


INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(1, 1);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(2, 2);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(3, 3);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(4, 4);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(5, 5);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(6, 6);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(7, 7);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(8, 8);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(9, 10);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(10, 12);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(11, 11);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(12, 13);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(13, 14);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(14, 14);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(15, 14);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(16, 17);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(17, 18);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(18, 18);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(19, 18);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(20, 18);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(21, 16);
INSERT INTO rooms_access_fields(accessFields_id, rooms_id) VALUES(22, 19);
